lint:
  actions_nf_test: false
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - assets/nf-core-metafactory_logo_light.png
  files_unchanged:
    - docs/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .prettierignore
  multiqc_config: false
  nextflow_config:
    - config_defaults:
        - params.msigdb_gene_sets
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: Ally Hawkins
  description: Nextflow pipeline for identifying metaprograms across single-cell/nuclei
    RNA-sequencing samples
  force: false
  is_nfcore: false
  name: metafactory
  org: AlexsLemonade
  outdir: .
  skip_features:
    - igenomes
    - multiqc
    - fastqc
    - codespaces
    - email
  version: 1.0.0dev
